routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Settings;

Route::get('/', 'frontendController@index');
//

Route::post('/email',function (){
    \Illuminate\Support\Facades\Mail::to('test@test.com')->send(new \App\Mail\contactEmail());
    session()->flash('success','Your email sent');
    return redirect()->back();

});

Auth::routes();

Route::get('/category/{id}', 'frontendController@category')->name('category.single');

Route::get('/search/result', function () {
    $post = \App\Post::where('title', 'like', '%' . request('query') . '%')->get();
    return view('results')->with('posts', $post)
        ->with('category', Category::take(5)->get())
        ->with('title', 'Search Result: '.request('query'))
        ->with('settings', Settings::first())
        ->with('query',request('query'));

});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('posts', 'postsController');
    Route::resource('category', 'categoriesController');
    Route::get('/trashed', 'postsController@trashed')->name('posts.trashed');
    Route::delete('/kill/{id}', 'postsController@kill')->name('posts.kill');
    Route::get('/restore/{id}', 'postsController@restore')->name('posts.restore');

    Route::resource('tag', 'tagsController');
    Route::resource('/users', 'UsersController');
    Route::get('/users/admin/{id}', 'UsersController@makeAdmin')->name('users.admin');
    Route::get('/users/admin/user/{id}', 'UsersController@makeNotAdmin')->name('users.user');

    Route::resource('/profiles/change', 'profileController');
    Route::get('/site/settings', 'SettingsController@edit')->name('settings.edit');
    Route::patch('/site/settings/update', 'SettingsController@update')->name('settings.update');

    Route::get('/home', 'HomeController@index')->name('home');



});

Route::get('/single/{id}', 'frontendController@single')->name('single.slug.index');

Route::get('/category/view/{id}','frontendController@category')->name('category.view');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function profile()
    {
        return $this->hasOne(profile::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }


}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\profile;
use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index')->with('users',User::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request,[
           'name'=>'required',
           'email'=>'required|email',
        ]);

        $user = User::create([
            'name'=>$request->name,
            'email'=>$request->email,
            'password'=>bcrypt('123456789'),
        ]);

        profile::create([
            'user_id'=>$user->id,
            'avatar' =>'/avatars/2.jpg'
        ]);



        session()->flash('success','user created');
        return redirect()->route('users.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        $user->profile->delete();
        $user->delete();
        session()->flash('success','user deleted');
        return redirect()->back();
    }

    public function makeAdmin($id){
        $user = User::find($id);
        $user->admin = 1;
        $user->save();
        session()->flash('success','success changed permission');
        return redirect()->back();

    }



    public function makeNotAdmin($id){
        $user = User::find($id);
        $user->admin = 0;
        $user->save();
        session()->flash('success','success changed permission');
        return redirect()->back();

    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Create New User
        </div>
        <div class="card-header">
            <form action="{{route('users.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="tag">Name</label>
                    <input type="text" name="name" class="form-control" value="{{old('name')}}">

                </div>

                <div class="form-group">
                    <label for="email">email</label>
                    <input type="email" name="email" class="form-control" value="{{old('email')}}">

                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store User</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content')


    <div class="card">

        <div class="card-body">
            <table class="table table-hover">
                <tr>
                    <th>image</th>
                    <th>name</th>
                    <th>Permissions</th>
                    <th>Delete</th>
                </tr>
                <tbody>
                @if($users->count() > 0)

                    @foreach($users as $user)
                        <tr>
                            <td>
                                <img src="{{asset($user->profile->avatar)}}" style="border-radius: 50%" width="80px"
                                     height="80px">
                            </td>
                            <td>
                                {{$user->name}}
                            </td>
                            <td>
                                @if($user->admin)
                                    <a href="{{route('users.user',['id'=>$user->id])}}" class="btn btn-danger">Remove permission</a>
                                @else
                                    <a href="{{route('users.admin',['id'=>$user->id])}}" class="btn btn-success">Make Admin</a>
                                @endif

                            </td>

                            <td>
                                @if(auth()->user()->id !== $user->id)
                                <form action="{{route('users.destroy',['id'=>$user->id])}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </form>
                                    @endif
                            </td>
                        </tr>

                    @endforeach
                @else
                    <tr>
                        <th colspan="5" class="text-center">No Users</th>
                    </tr>
                @endif


                </tbody>
            </table>
        </div>
    </div>



@endsection

resources/views/admin/users/profile.blade.php
@extends('layouts.app')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Edit User
        </div>
        <div class="card-header">
            <form action="{{route('change.update',['id'=>$user->id])}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('patch')
                <div class="form-group">
                    <label for="tag">Name</label>
                    <input type="text" name="name" class="form-control" value="{{$user->name}}">

                </div>

                <div class="form-group">
                     <label for="tag">email</label>
                    <input type="email" name="email" class="form-control" value="{{$user->email}}">

                </div>


                <div class="form-group">
                    <label for="password">password</label>
                    <input type="password" name="password" class="form-control" value="">

                </div>

                <div class="form-group">
                    <label for="avatar">upload your avatar</label>
                    <input type="file" name="avatar" class="form-control" value="">

                </div>

                <div class="form-group">
                    <label for="about">about</label>
                    <textarea class="form-control" name="about"  cols="6" rows="6">{{$user->profile->about}}</textarea>
                </div>

                <div class="form-group">
                    <label for="facebook">facebook</label>
                    <input type="text" name="facebook" class="form-control" value="{{$user->profile->facebook}}">

                </div>

                <div class="form-group">
                    <label for="youtube">youtube</label>
                    <input type="text" name="youtube" class="form-control" value="{{$user->profile->youtube}}">

                </div>

                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Update Profile</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection