routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Settings;

Route::get('/', 'frontendController@index');
//

Route::post('/email',function (){
    \Illuminate\Support\Facades\Mail::to('test@test.com')->send(new \App\Mail\contactEmail());
    session()->flash('success','Your email sent');
    return redirect()->back();

});

Auth::routes();

Route::get('/category/{id}', 'frontendController@category')->name('category.single');

Route::get('/search/result', function () {
    $post = \App\Post::where('title', 'like', '%' . request('query') . '%')->get();
    return view('results')->with('posts', $post)
        ->with('category', Category::take(5)->get())
        ->with('title', 'Search Result: '.request('query'))
        ->with('settings', Settings::first())
        ->with('query',request('query'));

});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('posts', 'postsController');
    Route::resource('category', 'categoriesController');
    Route::get('/trashed', 'postsController@trashed')->name('posts.trashed');
    Route::delete('/kill/{id}', 'postsController@kill')->name('posts.kill');
    Route::get('/restore/{id}', 'postsController@restore')->name('posts.restore');

    Route::resource('tag', 'tagsController');
    Route::resource('/users', 'UsersController');
    Route::get('/users/admin/{id}', 'UsersController@makeAdmin')->name('users.admin');
    Route::get('/users/admin/user/{id}', 'UsersController@makeNotAdmin')->name('users.user');

    Route::resource('/profiles/change', 'profileController');
    Route::get('/site/settings', 'SettingsController@edit')->name('settings.edit');
    Route::patch('/site/settings/update', 'SettingsController@update')->name('settings.update');

    Route::get('/home', 'HomeController@index')->name('home');



});

Route::get('/single/{id}', 'frontendController@single')->name('single.slug.index');

Route::get('/category/view/{id}','frontendController@category')->name('category.view');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['tag'];
    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/tagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class tagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tags.index',['tags'=>$tags]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request,[
           'tag'=>'required',
        ]);

        Tag::create([
            'tag'=>$request->tag,
        ]);

        session()->flash('success','tag created');
        return redirect()->route('tag.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('admin.tags.edit')->with('tags',$tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
           'tag'=>'required'
        ]);
        $tag = Tag::find($id);
        $tag->update([
            'tag'=>$request->tag,
        ]);

        session()->flash('success','tag updated');
        return redirect()->route('tag.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::destroy($id);
        session()->flash('success','tag Deleted');


        return redirect()->back();
    }
}

resources/views/admin/tags/create.blade.php
@extends('layouts.app')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Create New Tag
        </div>
        <div class="card-header">
            <form action="{{route('tag.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="tag">Name</label>
                    <input type="text" name="tag" class="form-control" value="{{old('tag')}}">

                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store Tag</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection

resources/views/admin/tags/edit.blade.php
@extends('layouts.app')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Edit Tag {{$tags->tag}}
        </div>
        <div class="card-header">
            <form action="{{route('tag.update',['id'=>$tags->id])}}" method="post">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="tag">Tag Name</label>
                    <input type="text" name="tag" class="form-control" value="{{$tags->tag}}">

                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store Tag</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.app')
@section('content')


    <div class="card">
        <div class="card-header">ALL Tags</div>

        <div class="card-body">
            <table class="table table-hover">
                <tr>
                    <th>Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                <tbody>
                @if($tags->count() > 0)
                    @foreach($tags as $tag)
                        <tr>
                            <td>{{$tag->tag}}</td>
                            <td>
                                <a href="{{route('tag.edit',['id'=>$tag->id])}}" class="btn btn-info">Edit</a>

                            </td>
                            <td>
                                <form action="{{route('tag.destroy',['id'=>$tag->id])}}" method="post">
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </td>
                        </tr>
                    @endforeach

                @else
                    <tr>
                        <th colspan="5" class="text-center">No Tags</th>
                    </tr>
                @endif


                </tbody>
            </table>
        </div>
    </div>



@endsection